### ISSUE TITLE
route issue

### ISSUE THREAD

**Issue by vanloswang** [fabric8io/gofabric8#198]
Install Origin 1.3 by openshift-ansible and deploy fabric8 on it. 
1. The route of fabric8 is http://fabric8.openshift-infra.vagrant.f8, but after access it by browser it changes to http://vagrant.f8. So I need to add two DNS record.
2. The route of the manageiq microservice is http://manageiq.openshift-infra.vagrant.f8, but the images use 443. So the route should be defined to https, not http.

**Comment by rawlingsj** [comment]
@vanloswang we've just released a new version of gofabric8 which has some improvements about auto detecting the api server.  I've successfully been deploying the fabric8 console to an openshift dedicated cluster using it so I hope issue 1 above is resolved.  For example I run..

```
gofabric8 deploy --pv=false --domain mydomain.fabric8.io
```

As for the second issue, that sounds like a bug.  I've raised this  https://github.com/fabric8io/exposecontroller/issues/9 for investigation and fix.  The expose controller is the service that creates those external URLs.

**Comment by vanloswang** [comment]
@rawlingsj your resolution of issue 1 is still not work for me. I deploy fabric8 by following cmd:
```bash
gofabric8 deploy --domain vanlos.fabric8.io
```
Then route of fabric8 console is 'http://fabric8.openshift-infra.vanlos.fabric8.io', and the hostname of fabric8 console is 'vanlos.fabric8.io'. There should be two DNS record for it too. It seems fabric8 will generate the route on Origin by project namespace name. Maybe we need some code change in gofabric8.

**Comment by vanloswang** [comment]
@rawlingsj my mistake, it works ok now, only one DNS record need to add.

**Comment by rawlingsj** [comment]
@vanloswang that's great news!  Are we ok to close this issue now that the second one you mentioned now linked in the exposecontroller project?
